# Generated by Django 3.0.8 on 2020-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10, unique=True)),
                ('catogery', models.CharField(max_length=10, unique=True)),
                ('qStatement', models.TextField()),
                ('qDescritpion', models.TextField()),
                ('qNote', models.TextField()),
                ('picture', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
