# Generated by Django 3.0.8 on 2020-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0002_auto_20200731_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogeries',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
