# Generated by Django 3.0.8 on 2020-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0003_auto_20200802_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
