# Generated by Django 3.0.8 on 2020-08-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0005_questiongroup_usercurrentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='catogery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashBoard.Catogeries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashBoard.Platforms'),
        ),
    ]
