# Generated by Django 3.0.8 on 2020-08-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0006_auto_20200804_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiongroup',
            old_name='catogery',
            new_name='catogery_FK',
        ),
        migrations.RenameField(
            model_name='questiongroup',
            old_name='platform',
            new_name='platform_FK',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='catogery',
            new_name='catogery_FK',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='platform',
            new_name='platform_FK',
        ),
        migrations.RenameField(
            model_name='usercurrentquestion',
            old_name='question',
            new_name='question_FK',
        ),
        migrations.RenameField(
            model_name='usercurrentquestion',
            old_name='user',
            new_name='user_FK',
        ),
    ]
