# Generated by Django 3.0.8 on 2020-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0007_auto_20200804_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentquestion',
            name='questionNumber_FK',
            field=models.IntegerField(default=0),
        ),
    ]
