# Generated by Django 3.0.8 on 2020-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0008_usercurrentquestion_questionnumber_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
