# Generated by Django 3.0.8 on 2020-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0010_questions_templatepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='templatePath',
            field=models.FilePathField(default='C:\\Pills\\LabVIEW\\General\x01\x01.vi', path='template'),
        ),
    ]
