# Generated by Django 3.0.8 on 2020-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0011_auto_20200805_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='templatePath',
            field=models.FilePathField(default='C:/Pills/LabVIEW/General/1/1.vi', path='template'),
        ),
    ]
