# Generated by Django 3.0.8 on 2020-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0012_auto_20200805_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='templatePath',
            field=models.FilePathField(blank=True, null=True, path='template'),
        ),
    ]
